language: python
script:
    - make
before_install:
install:
    - sudo apt-get update
    - sudo apt-get install pandoc pandoc-data
after_success:
    - bash .update-website.sh
env:
    global:
      secure: omzqxi7S0SMqEpBygeJjj4zW4PzR8FaPFzVdydNAbFtd/iBXsf4/KkLq3TyjDOWdP8Uxo/oemZSNyoz21HfOXNM0uam12TCpxSavDD3rK0nwXNhRILSxbltX+X9Uo3lgWkIxzW/OZmygCxZjI+7bIIPRioYp+q+ogtUHWcYhjtw=
